version: '3.4'
services:
  
  database:
    image: postgres:9.4
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - "./database-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Banco123*
      - PGDATA=/var/lib/postgresql/data
    privileged: true

volumes:
  database-data:
